export const SET_COURSE_LOADING = 'SET_COURSE_LOADING';

export const GET_COURSES = 'GET_COURSES';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';

export const ADD_COURSE = 'ADD_COURSE';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL';

export const UPDATE_COURSE = 'GUPDATE_COURSE';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_FAIL = 'UPDATE_COURSE_FAIL';

export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL';

export const GET_STUDENTS_BY_COURSE = 'GET_STUDENTS_BY_COURSE';
export const GET_STUDENTS_BY_COURSE_SUCCESS = 'GET_STUDENTS_BY_COURSE_SUCCESS';
export const GET_STUDENTS_BY_COURSE_FAIL = 'GET_STUDENTS_BY_COURSE_FAIL';

export const ADD_STUDENTS_TO_COURSE = 'ADD_STUDENTS_TO_COURSE';
export const ADD_STUDENTS_TO_COURSE_SUCCESS = 'ADD_STUDENTS_TO_COURSE_SUCCESS';
export const ADD_STUDENTS_TO_COURSE_FAIL = 'ADD_STUDENTS_TO_COURSE_FAIL';

export const REMOVE_STUDENT_FROM_COURSE = 'REMOVE_STUDENT_FROM_COURSE';
export const REMOVE_STUDENT_FROM_COURSE_SUCCESS =
  'REMOVE_STUDENT_FROM_COURSE_SUCCESS';
export const REMOVE_STUDENT_FROM_COURSE_FAIL =
  'REMOVE_STUDENT_FROM_COURSE_FAIL';
