variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  IMAGE_NAME: sardock01/cicdregistry
  IMAGE_TAG: CICD-BPA
  #DOCKER_HOST: tcp://localhost:2375/
  CI_REGISTRY_IMAGE: latest

default:
  image: maven:3.8.3-openjdk-17
  tags: 
  - docker
  services: 
  - docker:18.09.7-dind

stages:
  - build
  - test
  - package
  - build_image

# build:
#   stage: build
#   image: maven:3.8.3-openjdk-17
#   script:
#     - mvn -f backend/pom.xml install

#test:
#  stage: test
#  image: maven:3.8.3-openjdk-17
 # script:
#    - mvn -f backend/pom.xml test

package:
  stage: package
  script: 
     - echo "Maven Packaging Started"
     - mvn -f backend/pom.xml clean package
  artifacts:
    paths:
      - backend/target/*.jar
  only:
    - PX-22_CD_Implementation


build_image:
  stage: build_image
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - pwd
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker push $IMAGE_NAME:$IMAGE_TAG
  script:
    - echo "Docker Image Build"

  

