variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"


  
default:
  image: docker:19
  tags: 
  - rr11rr
  services: 
  - docker:dind --prviliged

stages:
  - build
  - test
  - package
  - deploy

# build:
#   stage: build
#   image: maven:3.8.3-openjdk-17
#   script:
#     - mvn -f backend/pom.xml install

# test:
#   stage: test
#   image: maven:3.8.3-openjdk-17
#   script:
#     - mvn -f backend/pom.xml test

package:
  stage: package
  image: maven:3.8.3-openjdk-17
  script: 
    - echo "Maven Packaging Started"
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
  only:
    - main

deploy:
  stage: deploy
  image: docker:19
  services: 
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - echo $USER
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_TEST_IMAGE
    - docker logout
  script:
    - echo $USER
    - echo "Maven Deployment Started"
