export const SET_STUDENT_DETAILS_LOADING = 'SET_STUDENT_DETAILS_LOADING';

export const GET_ENROLLED_COURSES_INFO = 'GET_ENROLLED_COURSES_INFO';
export const GET_ENROLLED_COURSES_INFO_SUCCESS =
  'GET_ENROLLED_COURSES_INFO_SUCCESS';
export const GET_ENROLLED_COURSES_INFO_FAIL = 'GET_ENROLLED_COURSES_INFO_FAIL';
