export const SET_USER_INFO_LOADING = 'SET_USER_INFO_LOADING';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const SET_RESET_PASSWORD_LOADING = 'SET_RESET_PASSWORD_LOADING';

export const GENERATE_RESET_PASSWORD_OTP = 'GENERATE_RESET_PASSWORD_OTP';
export const GENERATE_RESET_PASSWORD_OTP_SUCCESS =
  'GENERATE_RESET_PASSWORD_OTP_SUCCESS';
export const GENERATE_RESET_PASSWORD_OTP_FAIL =
  'GENERATE_RESET_PASSWORD_OTP_FAIL';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const RESET_PASSWORD_CHANGE_FLOW = 'RESET_PASSWORD_CHANGE_FLOW';

export const UPDATE_PROFILE_LOADING = 'UPDATE_PROFILE_LOADING';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
